### ISSUE TITLE
[Bug] AttributeError: 'LSS' object has no attribute 'setFilterPositionCount'

### ISSUE THREAD

**Issue by thezzk** [Robotics-Technology/Chess-Robot#1]
PS D:\Dev\GitRepo\ChessBotReproduceBug> python .\Interface.py
pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
<_io.TextIOWrapper name='params.txt' mode='r' encoding='cp936'>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\Interface.py", line 137, in pcTurn
    ac.executeMove(sequence["seq"], physicalParams, playerColor, homography, cap, selectedCam)
  File "D:\Dev\GitRepo\ChessBotReproduceBug\ArmControl.py", line 200, in executeMove
    shoulder.setFilterPositionCount(fpc)
AttributeError: 'LSS' object has no attribute 'setFilterPositionCount'

Reproduce procedure:
1. Start the robot arm
2. run "python <some directory>\.Interface.py"
3. Set "params.txt"
4. Press "New Game", play as white
5. Adjust the camera, place pieces, select "white zone"
6. Human player moves one white piece and ends his turn
7. The error message comes out

It seems that there is no definition of "setFilterPositionCount" inside "lss.py"

**Comment by geraldinebc** [comment]
Hello thezzk!
Sorry, I forgot to update the lss.py and lss_const.py libraries.
I added the definitions and it should work now :)
